version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
  - dependency-name: nodemon
    versions:
    - 2.0.6
  - dependency-name: js-yaml
    versions:
    - 3.14.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
